name: akademik_1
description: "Aplikasi Akademik Sekolah."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  google_fonts:
  flutter_svg:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - images/lepi.jpg
  - icons/Clock.svg
  - icons/Matemathic.svg
  - icons/Schedule.svg
  - icons/toa.svg
  - icons/Webinar.svg
  - icons/E-Learning.svg